version: "3"
services:
  api-dev:
    build:
      context: .
      args:
        - API_NAME=mini-pos-api
    ports:
      - "5000:3000"
    depends_on:
      - database

  database:
      image: mariadb:latest
      environment:
        MYSQL_DATABASE: mini_pos
        MYSQL_USER: mini_pos_api
        MYSQL_PASSWORD: mini_pos_api
        MYSQL_ROOT_PASSWORD: mini_pos_api_root
      volumes:
        - "./mariadb-data:/var/lib/mysql"
      ports:
        - "3333:3306"

volumes:
  mariadb-data:
