version: "3"
services:
  api-dev:
    build:
      context: .
      args:
        - API_NAME=mini-pos-api
    ports:
      - "5000:3000"
    depends_on:
      - database

  database:
      image: postgres:latest
      environment:
        POSTGRES_USER: mini_pos_api
        POSTGRES_PASSWORD: mini_pos_api
        POSTGRES_DB: mini_pos
      volumes:
        - "./postgres-data:/var/lib/postgresql/data"
      ports:
        - "5555:5432"

volumes:
  postgres-data: